import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";

const rubikSans = Rubik({
  variable: "--font-rubik-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubikSans.variable} ${rubikSans.className} antialiased text-[#1D2226] *:max-w-[23.475rem] *:bg-white *:min-h-screen bg-gray-200 flex justify-center`}
      >
        {children}
      </body>
    </html>
  );
}
